# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [7]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

M = np.random.randint(0, 100, size=(400, 100))
M

array([[46,  3, 97, ..., 63, 96, 28],
       [38, 18, 66, ..., 98, 86, 13],
       [ 0,  9, 39, ...,  7, 26, 84],
       ...,
       [40,  0, 83, ..., 49, 98, 88],
       [98, 35, 23, ..., 61,  0, 51],
       [20, 99, 18, ..., 67, 15, 30]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [6]:
#Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке.

M = np.random.randint(0, 100, size=(400, 100))
np.random.shuffle(M.T)
print(M)

[[44 30  0 ... 78 43 73]
 [ 8 63  5 ... 30 23 34]
 [98  9 59 ... 85 80 61]
 ...
 [63 82 21 ... 49 17 56]
 [78  8  5 ... 18 89 65]
 [58 73  8 ...  8 24 42]]


# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [5]:
#Generate a new array that contains only those rows of array `A` in which:
# - the sum of elements in even columns (indexes 0, 2,...) is greater than the average value (across the entire array) of the sum of elements in odd columns (indexes 1, 3,...).

M = np.random.randint(0, 100, size=(400, 100))
B = M[:, ::2]
C = M[:, 1::2]
D = B.sum(axis=1) > C.sum(axis=1).mean()
print(M[D])




[[72 84 52 ... 55 78 79]
 [74 82 82 ... 92 62 40]
 [93 82 62 ... 96 24 26]
 ...
 [27 48 29 ... 64 91 18]
 [81 45 38 ... 91 24  6]
 [34 57 86 ... 99  1 23]]


# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [8]:
# Find the index of the array string `M` in which the difference between the maximum and minimum element is maximal.

M = np.random.randint(0, 100, size=(200, 50))
difference = M.max(axis=1) - M.min(axis=1)
print(difference.argmax())


3


# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [9]:
# Generate an array of the same dimension as `A`, but in which each element is replaced by its ordinal number (starting from 1) in an ascending array of `A` elements.

M = np.random.randint(0, 100, size=(400, 150))
B = np.sort(M, axis=None)
C = np.argsort(B)
print(C.reshape(M.shape))
print(M)



[[    0   403   404 ...   358   359   360]
 [  353   306   457 ...   509   510   511]
 [  512   513   514 ...   150    45    47]
 ...
 [59778 59749 59768 ... 59895 59896 59897]
 [59898 59899 59900 ... 59470 59472 59473]
 [59474 59475 59476 ... 59621 59615 59999]]
[[50 66  4 ...  6 55 41]
 [94 22 61 ...  0 69  4]
 [30  1 66 ... 89 51 43]
 ...
 [33 72 15 ... 21 77 91]
 [51 48 72 ... 33 36 19]
 [38 39 89 ...  3 52 25]]


# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [10]:
# Apply min-max normalization to the rows of array `A'. 
# That is, you need to get a new array, in each row of which the maximum element is 1, the minimum is 0.

A = np.random.randint(0, 100, size=(200, 50))
B = A.max(axis=1)
C = A.min(axis=1)
D = (A - C[:, np.newaxis]) / (B - C)[:, np.newaxis]
print(D)


[[0.37113402 0.11340206 0.34020619 ... 0.25773196 0.22680412 0.        ]
 [0.76344086 0.05376344 0.19354839 ... 0.7311828  0.09677419 0.75268817]
 [0.68085106 0.87234043 0.94680851 ... 0.30851064 0.82978723 0.19148936]
 ...
 [0.93814433 0.98969072 0.77319588 ... 0.36082474 0.97938144 0.77319588]
 [0.         0.72164948 0.97938144 ... 0.4742268  0.84536082 0.59793814]
 [0.44329897 0.5257732  0.03092784 ... 0.43298969 0.30927835 0.60824742]]


# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [11]:
# Generate a new three-dimensional array of dimensions 10x200x50. The subarrays along the zero axis should consist of elements `A` multiplied by 1 - 10, respectively.

A = np.random.randint(0, 100, size=(200, 50))
B = np.arange(1, 11)
C = A * B[:, np.newaxis, np.newaxis]
print(C.shape)
print(C)


(10, 200, 50)
[[[ 85  42  93 ...   0  90  97]
  [ 77   4  52 ...  78  67  52]
  [ 40  78  70 ...  69  63  92]
  ...
  [ 40  89  24 ...  43  47  35]
  [ 44  96  49 ...  35  12  27]
  [ 42   8  50 ...  57  72  12]]

 [[170  84 186 ...   0 180 194]
  [154   8 104 ... 156 134 104]
  [ 80 156 140 ... 138 126 184]
  ...
  [ 80 178  48 ...  86  94  70]
  [ 88 192  98 ...  70  24  54]
  [ 84  16 100 ... 114 144  24]]

 [[255 126 279 ...   0 270 291]
  [231  12 156 ... 234 201 156]
  [120 234 210 ... 207 189 276]
  ...
  [120 267  72 ... 129 141 105]
  [132 288 147 ... 105  36  81]
  [126  24 150 ... 171 216  36]]

 ...

 [[680 336 744 ...   0 720 776]
  [616  32 416 ... 624 536 416]
  [320 624 560 ... 552 504 736]
  ...
  [320 712 192 ... 344 376 280]
  [352 768 392 ... 280  96 216]
  [336  64 400 ... 456 576  96]]

 [[765 378 837 ...   0 810 873]
  [693  36 468 ... 702 603 468]
  [360 702 630 ... 621 567 828]
  ...
  [360 801 216 ... 387 423 315]
  [396 864 441 ... 315 108 243]
  [378  72 450

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [12]:
# Create a new array of the same dimension as `A`, in which the even columns of `A` are grouped first, then the odd ones. Use [np.concat()] (https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html).

A = np.random.randint(0, 100, size=(200, 50))
B = A[:, ::2]
C = A[:, 1::2]
D = np.concatenate((B, C), axis=1)
print(D)


[[27 89 60 ... 25 24  1]
 [84 42 41 ... 29 28 34]
 [83 55 66 ... 66 10  1]
 ...
 [58 40 57 ...  5 71 94]
 [39 87 42 ... 56 90 79]
 [93 40 26 ... 55 68 88]]


# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [13]:
# Count the number of rows of the array `A`, in which all elements are greater than 5. Use [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = A > 5
C = np.all(B, axis=1)
print(C.sum())



14


# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [14]:
# Divide the array `A` horizontally into 10 parts and create a new array of dimension 20x50, which is the average of these parts. Use [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = np.split(A, 10, axis=0)
C = np.mean(B, axis=0)
print(C.shape)
print(C)



(20, 50)
[[48.3 56.8 37.  56.1 40.5 59.9 38.7 31.8 23.3 46.3 53.  37.8 48.5 44.
  52.6 50.8 62.6 29.6 47.8 60.7 57.8 52.  61.2 53.5 55.  43.7 55.4 51.
  58.9 28.  57.  35.6 38.4 45.1 48.7 51.  67.8 42.7 61.9 39.9 58.  51.4
  42.4 63.8 43.  46.3 40.4 49.5 57.3 56.1]
 [50.2 40.9 64.3 56.8 41.8 48.1 55.7 43.9 49.  49.5 59.8 50.  59.  47.6
  51.6 62.4 42.  48.1 42.9 55.2 47.3 50.2 46.2 59.3 64.  51.2 37.8 58.5
  58.5 61.9 40.5 31.6 58.9 52.2 47.9 37.  64.5 57.9 54.  38.9 47.5 41.6
  41.6 49.5 62.4 42.5 49.2 58.8 47.8 48.4]
 [45.5 59.6 48.9 56.9 62.9 48.7 53.4 57.2 50.3 53.1 53.6 54.6 59.9 61.8
  30.7 45.1 56.3 38.3 53.1 51.9 44.3 31.2 63.7 46.9 52.  22.9 52.8 47.9
  39.  31.3 50.5 60.5 51.6 42.2 49.6 63.  41.5 42.  40.3 49.3 37.5 54.6
  51.1 41.9 60.3 31.8 65.6 53.2 52.3 46.5]
 [33.7 55.7 55.3 42.  51.5 44.9 57.9 49.4 39.4 51.8 55.7 35.5 62.9 52.9
  44.5 51.9 49.4 54.7 50.8 38.6 28.9 55.2 38.1 35.8 50.3 52.6 36.8 57.3
  45.4 45.1 41.2 45.3 27.7 53.2 27.9 55.3 55.4 44.5 61.4 42.7 48.9 39.5


# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [15]:
#"Expand" the array `A` into a one-dimensional array. Leave only the unique elements in it in the same order in which they occur in the array. Use [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = np.unique(A)
print(B.shape)
print(B)



(100,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

In [16]:
# Create a one-dimensional array of dimension 200, in which each element is the Euclidean distance between the corresponding row `A` and the "middle" row `A`. Use [np.linalg.norm()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = A.mean(axis=0)
C = np.sqrt(((A - B) ** 2).sum(axis=1))
print(C.shape)
print(C)

(200,)
[188.58552635 219.84785819 223.00459805 188.0166236  210.89559206
 206.57120019 221.43010353 200.33891472 197.47840578 200.16555835
 204.62250793 191.17131257 215.61734798 209.10655358 180.58856761
 209.30848227 197.74380079 214.46142019 194.42770057 185.05134625
 225.04270872 224.85982467 213.37600791 201.32210696 203.5487675
 200.57180946 202.83653702 210.14635555 206.00342412 205.52761554
 204.67630725 194.10780703 197.74005854 221.2082972  192.07753838
 221.48763114 202.7805236  190.03410418 200.07551262 204.99527007
 201.91968886 183.59542682 220.38573173 187.36232479 192.64202748
 217.04753108 211.52628856 190.86139146 206.27569113 187.31647218
 182.23742961 214.05396691 224.52158192 184.29180869 184.70820434
 183.78348879 215.39243429 208.70462561 186.28784381 205.06962415
 210.21448749 203.56537218 208.95128798 200.8573393  204.81692008
 206.93675544 186.50933154 213.62783234 220.47993276 202.78232356
 157.91466287 160.95990417 207.45920262 225.41486364 172.17293849
 233

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [17]:
# Create a new array that consists of `A` elements modified according to the following rules:
# - if the element is less than 50, then it is multiplied by 2;
# - otherwise it is multiplied by 3.
# Use [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = np.where(A < 50, A * 2, A * 3)
print(B)


[[213  60 282 ...  98  40  26]
 [234  28  42 ...  56  42 282]
 [192  98  44 ...  30 189 198]
 ...
 [156   6 273 ... 186 267  50]
 [219 258  36 ... 267  10  94]
 [ 88  70   4 ... 270 216 156]]


# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [18]:
# Expand the array `A` into a one-dimensional array. Create three new arrays by calculating the moving averages of the windows 3, 5, 10. Find the sum of these arrays by aligning from the dimension with zeros on the right
# *Tip: Implement a function that counts the moving average. Use [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html ) or [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html )*

A = np.random.randint(0, 100, size=(200, 50))
B = np.concatenate((A, np.zeros((2, 50))), axis=0)
C = np.cumsum(B, axis=0)
D = C[3:] - C[:-3]
E = np.cumsum(B, axis=0)
F = E[5:] - E[:-5]
G = np.cumsum(B, axis=0)
H = G[10:] - G[:-10]
print(D.sum(axis=0))
print(F.sum(axis=0))
print(H.sum(axis=0))


[29235. 30763. 29160. 27206. 28630. 29161. 28525. 28470. 29421. 29217.
 29352. 29526. 27217. 30728. 29383. 27287. 27966. 29607. 29166. 30573.
 30216. 29637. 31081. 29700. 30277. 29383. 26983. 29186. 30123. 30114.
 31424. 28179. 29775. 31228. 28579. 28762. 30368. 31591. 28735. 31485.
 28654. 28988. 29779. 26935. 29987. 28965. 30794. 30176. 28204. 28597.]
[48345. 51008. 48218. 45076. 47394. 48338. 47073. 47226. 48583. 48187.
 48478. 48936. 45116. 50848. 48526. 44955. 46303. 48745. 48237. 50309.
 50007. 48952. 51380. 49355. 50118. 48713. 44488. 48519. 49883. 49720.
 51758. 46479. 49383. 51739. 47202. 47449. 50285. 52282. 47583. 51883.
 47512. 47871. 49357. 44359. 49719. 47993. 50904. 49886. 46619. 47325.]
[ 94210.  99599.  94128.  88656.  92587.  94482.  91321.  92716.  94717.
  93680.  94601.  96263.  88071.  98941.  94697.  87059.  90355.  95135.
  94091.  97202.  97627.  95474.  99743.  96336.  98419.  95709.  86700.
  95057.  97327.  96466. 100216.  90299.  96972. 100815.  92586.  926

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [19]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)  




[0, 0, 4, 4, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

In [20]:
# Implement this algorithm in a more optimal way on `numpy` arrays, without using loops. Check the correctness and identity of sampling algorithms using statistical tests.
def sample(x: np.ndarray, c: int) -> np.ndarray:
    assert len(x) > 0
    
    s = np.sum(x)
    val = s * np.random.random(size=c)
    idx = np.searchsorted(np.cumsum(x), val)
    return idx

# test
sample(np.array([50, 3, 1, 7, 20]), 5)


array([4, 0, 0, 0, 4], dtype=int64)

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [21]:
import random
import timeit 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)
# compare performance (using,`time it').
timeit.timeit('walk(10_000)', globals=globals(), number=1000)

7.32942809999804

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

In [22]:
# Implement a more efficient version using `numpy`, compare performance (using, for example, magic `time it'). Using [kdeplot()](https://seaborn.pydata.org/generated/seaborn .kdeplot.html ) or analogs, plot the distribution of the values of `walk(10_000)` on some reasonable number of launches.

import timeit
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import random


def walk_numpy(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += np.random.choice([-3, -1, 0, 2, 3])

    return cur_position

# test function walk_numpy
walk_numpy(10_000)
# compare performance (using,`time it').
timeit.timeit('walk_numpy(10_000)', globals=globals(), number=1000)



148.48930380000093

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [23]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


-0.07319525687531232

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.

In [19]:
# optimize function strange_conv using `Numba` and compare performance.ResourceWarning

import numba as nb
import numpy as np 
import numpy.typing as npt
import timeit

@nb.njit
def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t

a = np.random.random((10000, 10000))
strange_conv(a)

-0.15339751792773595